const sourceUrl = (brand, name) => `https://www.sephora.com/search?keyword=${encodeURIComponent(`${brand} ${name}`)}`;

const categoryLabels = {
  makeup: "Makeup",
  lips: "Lips",
  eyes: "Eyes",
  skincare: "Skincare",
  suncare: "Suncare",
  tools: "Tools"
};

const fallbackImages = {
  default: "assets/images/hero-products.jpg",
  makeup: "assets/images/hero-products.jpg",
  lips: "assets/images/lips-editorial.jpg",
  eyes: "assets/images/eyes-editorial.jpg",
  skincare: "assets/images/skincare-flatlay.jpg",
  suncare: "assets/images/sun-care.jpg",
  tools: "assets/images/beauty-tools.jpg",
  foundation: "assets/images/hero-portrait.jpg",
  cccream: "assets/images/hero-portrait.jpg",
  skintint: "assets/images/hero-products.jpg",
  concealer: "assets/images/showcase-detail.jpg",
  blush: "assets/images/showcase-artist.jpg",
  settingpowder: "assets/images/hero-products.jpg",
  settingspray: "assets/images/catalog-drops.jpg",
  highlighter: "assets/images/catalog-gloss.jpg",
  bronzer: "assets/images/hero-products.jpg",
  primer: "assets/images/catalog-drops.jpg",
  illuminator: "assets/images/catalog-gloss.jpg",
  lipstick: "assets/images/lips-editorial.jpg",
  lipoil: "assets/images/catalog-gloss.jpg",
  lipbalm: "assets/images/lips-editorial.jpg",
  lipmask: "assets/images/lips-editorial.jpg",
  lipliner: "assets/images/lips-editorial.jpg",
  liptint: "assets/images/lips-editorial.jpg",
  lipgloss: "assets/images/catalog-gloss.jpg",
  liptreatment: "assets/images/lips-editorial.jpg",
  lipscrub: "assets/images/lips-editorial.jpg",
  mascara: "assets/images/eyes-editorial.jpg",
  eyeshadow: "assets/images/eyes-editorial.jpg",
  eyeliner: "assets/images/showcase-detail.jpg",
  brow: "assets/images/eyes-editorial.jpg",
  serum: "assets/images/catalog-serum.jpg",
  moisturizer: "assets/images/moisturizer-editorial.jpg",
  cleanser: "assets/images/skincare-flatlay.jpg",
  mask: "assets/images/mask-treatment.jpg",
  eyecare: "assets/images/showcase-detail.jpg",
  sunscreen: "assets/images/sun-care.jpg",
  tool: "assets/images/beauty-tools.jpg"
};

const localImagePools = {
  makeup: [
    "assets/images/products/haus-labs-foundation.jpg",
    "assets/images/products/armani-luminous-silk.jpg",
    "assets/images/products/estee-lauder-double-wear.jpg",
    "assets/images/products/erborian-cc-cream.jpg",
    "assets/images/products/it-cosmetics-cc-cream.jpg",
    "assets/images/products/it-cosmetics-mini-cc-cream.jpg",
    "assets/images/products/tower28-concealer.jpg",
    "assets/images/products/nars-radiant-creamy.jpg",
    "assets/images/products/hourglass-concealer.jpg",
    "assets/images/products/rhode-pocket-blush.jpg",
    "assets/images/products/patrick-ta-blush.jpg",
    "assets/images/products/rare-soft-pinch-blush.jpg",
    "assets/images/products/huda-easy-bake.jpg",
    "assets/images/products/onesize-til-dawn-spray.jpg",
    "assets/images/products/charlotte-tilbury-setting-spray.jpg",
    "assets/images/products/rare-silky-highlighter.jpg",
    "assets/images/products/rare-liquid-luminizer.jpg",
    "assets/images/products/benefit-cookie-tickle.jpg",
    "assets/images/products/lys-bronzer-stick.jpg",
    "assets/images/products/milk-hydro-grip-primer.jpg",
    "assets/images/products/onesize-mini-primer.jpg",
    "assets/images/products/saie-glowy-super-gel.jpg",
    "assets/images/products/saie-mini-glowy.jpg",
    "assets/images/hero-products.jpg",
    "assets/images/showcase-artist.jpg",
    "assets/images/showcase-detail.jpg"
  ],
  lips: [
    "assets/images/lips-editorial.jpg",
    "assets/images/catalog-gloss.jpg",
    "assets/images/showcase-detail.jpg",
    "assets/images/hero-products.jpg"
  ],
  eyes: [
    "assets/images/products/sephora-size-up-mascara.jpg",
    "assets/images/eyes-editorial.jpg",
    "assets/images/showcase-detail.jpg",
    "assets/images/hero-products.jpg"
  ],
  skincare: [
    "assets/images/catalog-serum.jpg",
    "assets/images/skincare-flatlay.jpg",
    "assets/images/moisturizer-editorial.jpg",
    "assets/images/mask-treatment.jpg",
    "assets/images/hero-skincare.jpg"
  ],
  suncare: [
    "assets/images/sun-care.jpg",
    "assets/images/hero-skincare.jpg",
    "assets/images/skincare-flatlay.jpg"
  ],
  tools: [
    "assets/images/beauty-tools.jpg",
    "assets/images/catalog-tool.jpg",
    "assets/images/hero-products.jpg"
  ]
};

const descriptionMap = {
  foundation: "Base pensada para una complexion pulida, profesional y lista para sesiones o eventos.",
  cccream: "Cobertura ligera a media con acabado perfeccionador para looks limpios y radiantes.",
  skintint: "Cobertura ligera con sensacion fresca para una tienda beauty con enfoque actual.",
  concealer: "Corrector de alto interes visual para perfeccionar ojeras y detalles del rostro.",
  blush: "Rubor de acabado moderno pensado para dar color, dimension y efecto healthy skin.",
  settingpowder: "Polvo ideal para sellar maquillaje y mantener un acabado mas uniforme.",
  settingspray: "Spray fijador disenado para extender duracion y reforzar la experiencia glam.",
  highlighter: "Iluminador para elevar puntos altos del rostro con brillo mas refinado.",
  bronzer: "Bronzer para aportar calidez, contorno suave y presencia editorial al look.",
  primer: "Primer para preparar la piel y mejorar la base antes de aplicar maquillaje.",
  illuminator: "Glow booster para mezclar o usar solo y dar un acabado luminoso premium.",
  lipstick: "Color de labios con acabado llamativo y presencia visual fuerte para la vitrina online.",
  lipoil: "Aceite o gloss de labios con brillo jugoso, ideal para una categoria aspiracional.",
  lipbalm: "Cuidado de labios enfocado en hidratacion diaria y confort cosmetico.",
  lipmask: "Tratamiento nocturno o intensivo para nutrir labios y sumar valor al carrito.",
  lipliner: "Perfilador pensado para definir contorno y mejorar la duracion del labial.",
  liptint: "Color ligero con enfoque en hidratacion y look natural de larga presencia.",
  lipgloss: "Gloss o glaze de brillo alto para una coleccion de labios mas comercial.",
  liptreatment: "Tratamiento cosmetico para labios con enfoque en cuidado y acabado saludable.",
  lipscrub: "Exfoliacion suave para una rutina de labios completa dentro de la tienda.",
  mascara: "Mascara pensada para volumen, definicion o efecto tubing dentro del universo eye.",
  eyeshadow: "Sombra para construir looks mas completos y visualmente atractivos.",
  eyeliner: "Eyeliner para trazar definicion precisa y ampliar la coleccion de ojos.",
  brow: "Producto de cejas para definir, peinar o rellenar con acabado mas pulido.",
  serum: "Tratamiento concentrado de skincare para una oferta mas profesional y completa.",
  moisturizer: "Hidratante pensada para reforzar rutinas de cuidado con textura y beneficio claro.",
  cleanser: "Limpiador de uso diario que equilibra el catalogo entre color y cuidado.",
  mask: "Mascara de tratamiento para sumar experiencias spa y rituales de belleza.",
  eyecare: "Cuidado del contorno de ojos para una seleccion de tratamiento mas premium.",
  sunscreen: "Proteccion solar para venta online con enfoque en cuidado y uso diario.",
  tool: "Herramienta beauty para complementar aplicaciones y mejorar la experiencia de compra."
};

const normalizeKey = (value) => String(value).toLowerCase().replace(/[^a-z0-9]+/g, "");
const isExternalUrl = (value) => /^https?:\/\//i.test(String(value || ""));
const getPoolImage = (category, subcategoryKey, index) => {
  const specific = fallbackImages[subcategoryKey];
  const pool = localImagePools[category] || [fallbackImages.default];
  return specific || pool[index % pool.length] || fallbackImages.default;
};

const catalogSeed = [
  ["HAUS LABS BY LADY GAGA", "Triclone Skin Tech Medium Coverage Foundation with Fermented Arnica", "makeup", "Foundation", 52.0, "$52.00", "assets/images/products/haus-labs-foundation.jpg"],
  ["Armani Beauty", "Luminous Silk Natural Glow Blurring Liquid Foundation with 24 Hour Wear", "makeup", "Foundation", 48.0, "$48.00 - $69.00", "assets/images/products/armani-luminous-silk.jpg"],
  ["Estee Lauder", "NEW Double Wear Stay-in-Place Lightweight Matte Foundation with 36H Wear", "makeup", "Foundation", 10.0, "$10.00 - $52.00", "assets/images/products/estee-lauder-double-wear.jpg"],
  ["Erborian", "CC Cream Color-Corrector for Natural Luminous Finish with Korean Centella Asiatica Extract", "makeup", "CC Cream", 26.0, "$26.00 - $46.00", "assets/images/products/erborian-cc-cream.jpg"],
  ["IT Cosmetics", "CC+ Cream Full Coverage Color Correcting Foundation with SPF 50+", "makeup", "CC Cream", 22.0, "$22.00 - $47.00", "assets/images/products/it-cosmetics-cc-cream.jpg"],
  ["Summer Fridays", "Sheer Skin Tint with Hyaluronic Acid + Squalane", "makeup", "Skin Tint", 42.0, "$42.00", "assets/images/products/summer-fridays-skin-tint.jpg"],
  ["IT Cosmetics", "Mini CC+ Cream Full Coverage Color Correcting Foundation with SPF 50+", "makeup", "CC Cream", 22.0, "$22.00", "assets/images/products/it-cosmetics-mini-cc-cream.jpg"],
  ["MILK MAKEUP", "Hydro Grip 12-Hour Hydrating Gel Skin Tint", "makeup", "Skin Tint", 38.0, "$38.00"],
  ["Tower 28 Beauty", "Swipe All-Over Hydrating Serum Concealer with 18-HR Wear", "makeup", "Concealer", 24.0, "$24.00", "assets/images/products/tower28-concealer.jpg"],
  ["NARS", "Radiant Creamy Concealer with Hydrating Medium Coverage", "makeup", "Concealer", 17.0, "$17.00 - $36.00", "assets/images/products/nars-radiant-creamy.jpg"],
  ["Hourglass", "Vanish Airbrush Concealer", "makeup", "Concealer", 20.0, "$20.00 - $39.00", "assets/images/products/hourglass-concealer.jpg"],
  ["rhode", "Pocket Blush Buildable Hydrating Cream Blush", "makeup", "Blush", 25.0, "$25.00", "assets/images/products/rhode-pocket-blush.jpg"],
  ["PATRICK TA", "Major Headlines Double-Take Creme & Powder Blush Duo", "makeup", "Blush", 25.0, "$25.00 - $40.00", "assets/images/products/patrick-ta-blush.jpg"],
  ["Rare Beauty", "Soft Pinch Liquid Blush", "makeup", "Blush", 16.0, "$16.00 - $25.00", "assets/images/products/rare-soft-pinch-blush.jpg"],
  ["HUDA BEAUTY", "Easy Bake Blurring Loose Baking & Setting Powder", "makeup", "Setting Powder", 23.0, "$23.00 - $39.00", "assets/images/products/huda-easy-bake.jpg"],
  ["ONE/SIZE", "On 'Til Dawn Mattifying Waterproof Setting Spray", "makeup", "Setting Spray", 18.0, "$18.00 - $34.00", "assets/images/products/onesize-til-dawn-spray.jpg"],
  ["Charlotte Tilbury", "Airbrush Flawless Hydrating & Waterproof Setting Spray", "makeup", "Setting Spray", 25.0, "$25.00 - $59.00", "assets/images/products/charlotte-tilbury-setting-spray.jpg"],
  ["Rare Beauty", "Positive Light Silky Touch Highlighter", "makeup", "Highlighter", 28.0, "$28.00", "assets/images/products/rare-silky-highlighter.jpg"],
  ["Saie", "Mini Glowy Super Gel Illuminator", "makeup", "Illuminator", 17.0, "$17.00", "assets/images/products/saie-mini-glowy.jpg"],
  ["Rare Beauty", "Positive Light Liquid Luminizer Highlight", "makeup", "Highlighter", 18.0, "$18.00 - $28.00", "assets/images/products/rare-liquid-luminizer.jpg"],
  ["Benefit Cosmetics", "Cookie and Tickle Shimmer Finish Powder Highlighters", "makeup", "Highlighter", 39.0, "$39.00", "assets/images/products/benefit-cookie-tickle.jpg"],
  ["LYS Beauty", "No Limits Cream Bronzer and Contour Stick", "makeup", "Bronzer", 24.0, "$24.00", "assets/images/products/lys-bronzer-stick.jpg"],
  ["Gucci", "Poudre De Beaute Eclat Soleil Bronzing Powder", "makeup", "Bronzer", 69.0, "$69.00"],
  ["MILK MAKEUP", "Hydro Grip Hydrating Makeup Primer with Niacinamide", "makeup", "Primer", 20.0, "$20.00 - $38.00", "assets/images/products/milk-hydro-grip-primer.jpg"],
  ["ONE/SIZE", "Mini Secure The Sweat Waterproof Mattifying Primer", "makeup", "Primer", 15.0, "$15.00", "assets/images/products/onesize-mini-primer.jpg"],
  ["Saie", "Glowy Super Gel Lightweight Dewy Multipurpose Illuminator", "makeup", "Illuminator", 17.0, "$17.00 - $29.00", "assets/images/products/saie-glowy-super-gel.jpg"],
  ["FENTY BEAUTY by Rihanna", "Gloss Bomb Stix High-Shine Gloss Stick", "lips", "Lipstick", 26.0, "$26.00"],
  ["Yves Saint Laurent", "Loveshine Plumping Lip Oil Gloss", "lips", "Lip Oil", 40.0, "$40.00"],
  ["Yves Saint Laurent", "YSL Loveshine High Shine Lipstick", "lips", "Lipstick", 45.0, "$45.00"],
  ["LANEIGE", "Lip Glowy Balm", "lips", "Lip Balm", 19.0, "$19.00"],
  ["Summer Fridays", "Lip Butter Balm for Hydration + Shine", "lips", "Lip Balm", 24.0, "$24.00"],
  ["Tatcha", "Kissu Lip Tint SPF 25 Hydrating Mineral Sunscreen", "lips", "Lip Tint", 32.0, "$32.00"],
  ["Ole Henriksen", "Pout Preserve Hydrating Peptide Lip Treatment", "lips", "Lip Treatment", 23.0, "$23.00"],
  ["Kaja", "Jelly Charm Glaze Stick", "lips", "Lip Gloss", 20.0, "$20.00"],
  ["Topicals", "Slick Salve", "lips", "Lip Balm", 16.0, "$16.00"],
  ["Tatcha", "The Kissu Lip Mask", "lips", "Lip Mask", 29.0, "$29.00"],
  ["Fresh", "Sugar Lip Balm Hydrating Treatment", "lips", "Lip Balm", 20.0, "$20.00"],
  ["Mario Badescu", "Moisturizing Lip Balm for Dry Lips", "lips", "Lip Balm", 8.0, "$8.00"],
  ["Glow Recipe", "Plum Plump Hyaluronic Lip Balm", "lips", "Lip Balm", 19.0, "$19.00"],
  ["Fresh", "Sugar Advanced Therapy Treatment Lip Balm", "lips", "Lip Balm", 29.0, "$29.00"],
  ["Tatcha", "The Kissu Lip Scrub", "lips", "Lip Scrub", 17.0, "$17.00"],
  ["The INKEY List", "Tripeptide Plumping Lip Balm", "lips", "Lip Balm", 13.0, "$13.00"],
  ["Gisou", "Honey Infused Hydrating Lip Oil", "lips", "Lip Oil", 28.0, "$28.00"],
  ["Biossance", "Squalane + Rose Vegan Lip Balm", "lips", "Lip Balm", 18.0, "$18.00"],
  ["SEPHORA COLLECTION", "Melting Lip Clicks Balm + Shine", "lips", "Lip Balm", 16.0, "$16.00"],
  ["Fenty Beauty", "Plush Puddin' Intensive Recovery Lip Mask", "lips", "Lip Mask", 23.0, "$23.00"],
  ["iNNBEAUTY PROJECT", "Glaze Lip Oil", "lips", "Lip Oil", 18.0, "$18.00"],
  ["Kosas", "Wet Lip Oil Gloss", "lips", "Lip Oil", 22.0, "$22.00"],
  ["LANEIGE", "Lip Sleeping Mask Intense Hydration with Vitamin C", "lips", "Lip Mask", 24.0, "$24.00"],
  ["MAKE UP FOR EVER", "Artist Color Pencil Longwear Lip Liner", "lips", "Lip Liner", 24.0, "$24.00"],
  ["Charlotte Tilbury", "Lip Cheat Contour Duo Lip Liner", "lips", "Lip Liner", 25.0, "$25.00"],
  ["HUDA BEAUTY", "Lip Contour 2.0 Automatic Matte Lip Pencil", "lips", "Lip Liner", 21.0, "$21.00"],
  ["Natasha Denona", "I Need A Lip Crayon", "lips", "Lip Liner", 24.0, "$24.00"],
  ["Refy", "Lip Sculpt Longwear Shape and Fill Lip Liner", "lips", "Lip Liner", 24.0, "$24.00"],
  ["Rare Beauty", "Kind Words Matte Lip Liner", "lips", "Lip Liner", 18.0, "$18.00"],
  ["Dior", "Rouge Dior Contour Lip Liner", "lips", "Lip Liner", 35.0, "$35.00"],
  ["Hourglass", "Shape and Sculpt Lip Liner", "lips", "Lip Liner", 34.0, "$34.00"],
  ["Morphe", "Color Pencil Lip Liner", "lips", "Lip Liner", 6.0, "$6.00"],
  ["SEPHORA COLLECTION", "Rouge Gel Lip Liner", "lips", "Lip Liner", 13.0, "$13.00"],
  ["SEPHORA COLLECTION", "Colorful Eyeshadow", "eyes", "Eyeshadow", 6.0, "$6.00 - $9.00"],
  ["Urban Decay", "24/7 Eyeshadow Single", "eyes", "Eyeshadow", 23.0, "$23.00"],
  ["Charlotte Tilbury", "Eyes to Mesmerise Long-Lasting Cream Eyeshadow", "eyes", "Eyeshadow", 25.0, "$25.00 - $35.00"],
  ["SEPHORA COLLECTION", "Size Up Volumizing Mascara", "eyes", "Mascara", 16.0, "$16.00", "assets/images/products/sephora-size-up-mascara.jpg"],
  ["Benefit Cosmetics", "BADgal BANG! Volumizing Mascara", "eyes", "Mascara", 30.0, "$30.00"],
  ["Kulfi", "Badi Lash Smudge Proof Volumizing Tubing Mascara", "eyes", "Mascara", 25.0, "$25.00"],
  ["Rabanne", "Drama Waterproof Mascara & Iconic Lip Gloss Duo", "eyes", "Mascara", 31.0, "$31.00"],
  ["Grande Cosmetics", "GrandeMASCARA Conditioning Peptide Mascara", "eyes", "Mascara", 25.0, "$25.00"],
  ["Too Faced", "Better Than Sex Volumizing and Lengthening Mascara", "eyes", "Mascara", 17.0, "$17.00 - $30.00"],
  ["Lancome", "Lash Idole Lengthening & Volumizing Mascara", "eyes", "Mascara", 16.0, "$16.00 - $32.00"],
  ["Rare Beauty", "Perfect Strokes Universal Volumizing Mascara", "eyes", "Mascara", 22.0, "$22.00"],
  ["Tower 28 Beauty", "MakeWaves Lengthening + Volumizing Mascara", "eyes", "Mascara", 20.0, "$20.00"],
  ["Benefit Cosmetics", "Fan Fest Fanning & Volumizing Mascara", "eyes", "Mascara", 29.0, "$29.00"],
  ["Yves Saint Laurent", "Lash Clash Extreme Volume Mascara", "eyes", "Mascara", 16.0, "$16.00 - $32.00"],
  ["ILIA", "Fullest Volumizing Mascara", "eyes", "Mascara", 28.0, "$28.00"],
  ["Too Faced", "Ribbon Wrapped Lash Extreme Lengthening Mascara", "eyes", "Mascara", 30.0, "$30.00"],
  ["Anastasia Beverly Hills", "Lash Sculpt Lengthening & Volumizing Mascara", "eyes", "Mascara", 16.0, "$16.00 - $28.00"],
  ["Tarte", "tartelette Tubing Mascara", "eyes", "Mascara", 15.0, "$15.00 - $28.00"],
  ["GUCCI", "Le Magnetisme Mascara", "eyes", "Mascara", 38.0, "$38.00"],
  ["KVD Beauty", "Full Sleeve Long + Defined Tubing Mascara", "eyes", "Mascara", 26.0, "$26.00"],
  ["Caliray", "Come Hell or High Water Volumizing + Lengthening + Curling Tubing Mascara", "eyes", "Mascara", 15.0, "$15.00 - $25.00"],
  ["Clinique", "High Impact High-Fi Full Volume Mascara", "eyes", "Mascara", 33.0, "$33.00"],
  ["Milk Makeup", "RISE Lifting + Lengthening Mascara", "eyes", "Mascara", 14.0, "$14.00 - $28.00"],
  ["SEPHORA COLLECTION", "Colorful Waterproof Eyeshadow & Eyeliner Multi-Stick", "eyes", "Eyeliner", 7.0, "$7.00"],
  ["ONE/SIZE", "Line Sinker Longwear Gel Eyeliner", "eyes", "Eyeliner", 14.0, "$14.00"],
  ["Valentino", "Twin Liner Gel and Liquid Eyeliner", "eyes", "Eyeliner", 47.0, "$47.00"],
  ["Benefit Cosmetics", "Precisely, My Brow Detailer Micro-Fine Precision Pencil", "eyes", "Brow", 15.0, "$15.00 - $29.00"],
  ["Benefit Cosmetics", "24-HR Brow Setter Clear Brow Gel", "eyes", "Brow", 16.0, "$16.00 - $29.00"],
  ["Benefit Cosmetics", "Mighty Fine Brow Pen Microfilling Brow Tint", "eyes", "Brow", 29.0, "$29.00"],
  ["The Ordinary", "Hyaluronic Acid 2% + B5 Hydrating Serum", "skincare", "Serum", 9.9, "$9.90"],
  ["Caudalie", "Vinoperfect Brightening Dark Spot Vitamin C Face Serum", "skincare", "Serum", 89.0, "$89.00"],
  ["Glow Recipe", "Watermelon Glow Niacinamide Hue Drops Serum", "skincare", "Serum", 18.0, "$18.00 - $36.00"],
  ["Tatcha", "The Dewy Serum Resurfacing and Plumping Treatment", "skincare", "Serum", 90.0, "$90.00"],
  ["Sunday Riley", "C.E.O. Glow Vitamin C + Turmeric Face Oil", "skincare", "Serum", 40.0, "$40.00 - $80.00"],
  ["Tatcha", "The Brightening Serum with Vitamin C + Niacinamide", "skincare", "Serum", 95.0, "$95.00"],
  ["Dior", "Capture Le Serum Hyalushot Wrinkle Corrector", "skincare", "Serum", 95.0, "$95.00"],
  ["Drunk Elephant", "T.L.C. Framboos Glycolic Night Serum", "skincare", "Serum", 54.0, "$54.00 - $96.00"],
  ["Paula's Choice", "25% Vitamin C + Glutathione Clinical Serum", "skincare", "Serum", 71.0, "$71.00"],
  ["Kiehl's Since 1851", "Ultra Facial Cream with Squalane", "skincare", "Moisturizer", 24.0, "$24.00 - $70.00"],
  ["La Roche-Posay", "Toleriane Double Repair Face Moisturizer with Ceramide and Niacinamide", "skincare", "Moisturizer", 24.99, "$24.99"],
  ["Tatcha", "The Dewy Skin Cream Plumping + Hydrating Refillable Moisturizer", "skincare", "Moisturizer", 24.0, "$24.00 - $89.00"],
  ["Youth To The People", "Superfood Air-Whip Lightweight Face Moisturizer with Hyaluronic Acid", "skincare", "Moisturizer", 16.0, "$16.00 - $54.00"],
  ["Skinfix", "Barrier+ Triple Lipid-Peptide Refillable Face Cream", "skincare", "Moisturizer", 20.0, "$20.00 - $78.00"],
  ["First Aid Beauty", "Ultra Repair Firming Collagen Cream with Peptides and Niacinamide", "skincare", "Moisturizer", 46.0, "$46.00"],
  ["Summer Fridays", "Rich Cushion Cream Ultra Plumping Moisturizer", "skincare", "Moisturizer", 58.0, "$58.00"],
  ["BYOMA", "Moisturizing Rich Cream with Tri-Ceramide Complex + Shea Extract", "skincare", "Moisturizer", 16.99, "$16.99"],
  ["La Mer", "Creme de la Mer Moisturizing Cream", "skincare", "Moisturizer", 100.0, "$100.00 - $610.00"],
  ["The INKEY List", "Omega Water Cream Moisturizer", "skincare", "Moisturizer", 12.0, "$12.00"],
  ["Tatcha", "The Water Cream Oil-Free Pore Minimizing Moisturizer", "skincare", "Moisturizer", 24.0, "$24.00 - $89.00"],
  ["Drunk Elephant", "Protini Polypeptide Firming Refillable Moisturizer", "skincare", "Moisturizer", 24.0, "$24.00 - $98.00"],
  ["Glow Recipe", "Plum Plump Hyaluronic Acid Moisturizer", "skincare", "Moisturizer", 39.0, "$39.00"],
  ["Tatcha", "The Rice Wash Skin-Softening Cleanser", "skincare", "Cleanser", 18.0, "$18.00 - $40.00"],
  ["Fresh", "Soy Hydrating Gentle Face Cleanser", "skincare", "Cleanser", 16.0, "$16.00 - $39.00"],
  ["Youth To The People", "Superfood Gentle Antioxidant Refillable Cleanser", "skincare", "Cleanser", 16.0, "$16.00 - $39.00"],
  ["Kiehl's Since 1851", "Ultra Facial Cleanser", "skincare", "Cleanser", 16.0, "$16.00 - $32.00"],
  ["Summer Fridays", "Super Amino Gel Cleanser", "skincare", "Cleanser", 19.0, "$19.00 - $38.00"],
  ["SEPHORA COLLECTION", "Clean Me Up Clarifying Cleanser", "skincare", "Cleanser", 16.0, "$16.00"],
  ["Farmacy", "Green Clean Makeup Removing Cleansing Balm", "skincare", "Cleanser", 15.0, "$15.00 - $39.00"],
  ["The INKEY List", "Oat Makeup Removing Cleansing Balm", "skincare", "Cleanser", 13.0, "$13.00"],
  ["Drunk Elephant", "Beste No. 9 Jelly Cleanser", "skincare", "Cleanser", 16.0, "$16.00 - $36.00"],
  ["Summer Fridays", "Jet Lag Mask + Moisturizer with Niacinamide", "skincare", "Mask", 26.0, "$26.00 - $49.00"],
  ["Tatcha", "Violet-C Radiance Mask with Vitamin C", "skincare", "Mask", 72.0, "$72.00"],
  ["Dr. Jart+", "Cicapair Tiger Grass Calming Mask", "skincare", "Mask", 58.0, "$58.00"],
  ["Peter Thomas Roth", "Cucumber Gel Mask", "skincare", "Mask", 20.0, "$20.00 - $55.00"],
  ["Fenty Skin", "Cookies N Clean Whipped Clay Detox Face Mask", "skincare", "Mask", 35.0, "$35.00"],
  ["fresh", "Rose Face Mask", "skincare", "Mask", 20.0, "$20.00 - $68.00"],
  ["Summer Fridays", "Overtime Mask", "skincare", "Mask", 46.0, "$46.00"],
  ["First Aid Beauty", "5 in 1 Bouncy Mask", "skincare", "Mask", 32.0, "$32.00"],
  ["SEPHORA COLLECTION", "Caffeine Eye Masks", "skincare", "Eye Care", 4.0, "$4.00"],
  ["Dr. Dennis Gross Skincare", "DermInfusions Fill + Repair Eye Cream", "skincare", "Eye Care", 76.0, "$76.00"],
  ["Glow Recipe", "Guava Vitamin C Bright-Eye Gel Cream", "skincare", "Eye Care", 42.0, "$42.00"],
  ["The INKEY List", "Brighten-i Eye Cream", "skincare", "Eye Care", 14.0, "$14.00"],
  ["Sulwhasoo", "Concentrated Ginseng Rejuvenating Eye Cream", "skincare", "Eye Care", 138.0, "$138.00"],
  ["Supergoop!", "Unseen Sunscreen SPF 40", "suncare", "Sunscreen", 22.0, "$22.00 - $40.00"],
  ["Dr. Dennis Gross Skincare", "All-Physical Ultimate Defense Broad Spectrum Sunscreen SPF 50 PA++++", "suncare", "Sunscreen", 44.0, "$44.00"],
  ["EltaMD", "UV Clear Broad-Spectrum SPF 46 Face Sunscreen", "suncare", "Sunscreen", 20.0, "$20.00 - $44.00"],
  ["Tatcha", "The Silk Sunscreen SPF 50 Weightless Mineral Sunscreen", "suncare", "Sunscreen", 64.0, "$64.00"],
  ["Vacation", "Classic Lotion SPF 50 Sunscreen", "suncare", "Sunscreen", 16.0, "$16.00 - $22.00"],
  ["Kiehl's Since 1851", "Better Screen UV Serum SPF 50+ Sunscreen", "suncare", "Sunscreen", 46.0, "$46.00"],
  ["Tower 28 Beauty", "SunnyDays SPF 30 Tinted Sunscreen Foundation", "suncare", "Sunscreen", 32.0, "$32.00"],
  ["Supergoop!", "Glowscreen SPF 40", "suncare", "Sunscreen", 22.0, "$22.00 - $40.00"],
  ["Cay Skin", "Isle Glow Face Lotion SPF 45", "suncare", "Sunscreen", 14.0, "$14.00 - $34.00"],
  ["Beautyblender", "Original Makeup Sponge", "tools", "Tool", 20.0, "$20.00"]
];

const realCatalogData = window.catalogRealData || {};

window.catalogProducts = catalogSeed.map((item, index) => {
  const [brand, name, category, subcategory, price, priceLabel, image] = item;
  const productId = `mbl-product-${String(index + 1).padStart(3, "0")}`;
  const subcategoryKey = normalizeKey(subcategory);
  const fallbackImage = getPoolImage(category, subcategoryKey, index);
  const hasExactSeedImage = Boolean(image && !isExternalUrl(image) && /^assets\/images\/products\//.test(image));
  const localImage = hasExactSeedImage ? image : fallbackImage;
  const realEntry = realCatalogData[productId] || {};
  const verifiedImage = Boolean(realEntry.verified || hasExactSeedImage);
  const finalImage = realEntry.image || localImage;
  const finalSourceUrl = realEntry.sourceUrl || sourceUrl(brand, name);
  const finalSourceLabel = realEntry.sourceUrl ? "Ver en Sephora" : "Buscar en Sephora";

  return {
    id: productId,
    brand,
    name,
    category,
    categoryLabel: categoryLabels[category] || "Beauty",
    subcategory,
    price,
    priceLabel,
    image: finalImage,
    fallbackImage,
    badge: subcategory,
    description: descriptionMap[subcategoryKey] || "Seleccion profesional curada para una tienda online de belleza.",
    sourceUrl: finalSourceUrl,
    sourceLabel: finalSourceLabel,
    featuredOrder: index + 1,
    isVerifiedImage: verifiedImage
  };
}).filter((product) => product.isVerifiedImage);
